### ISSUE TITLE
Set commands to real ones

### ISSUE THREAD

**Issue by robert-beckley** [TreeboMC/TreeboTeleport#21]
change 
/tp2mepls to /tpahere 
/tp2player to /tp
/tp2pos to /tp
/tpok - add /tpyes & /tpaccept
/matitp tp /tpa <player>
/acidislands to /acidisland

 Remove /ttwild 
remove merge ess commands once done

**Comment by ShakeforProtein** [comment]
tp2mepls - done
tp2player - merged into /tp
tp2pos - merged into /tp
tp2worldat - merged into /tp
tp2me - merged into /tp
tpaccept etc - done
mayitp - done
acidislands - Config issue. Wont fix. servers.yml, change name of key
ttwild - done
