### ISSUE TITLE
List Other Players Homes

### ISSUE THREAD

**Issue by robert-beckley** [TreeboMC/TreeboTeleport#3]
/homes < playername >
Lists all homes from target player

**Comment by ShakeforProtein** [comment]
Implemented

**Comment by ShakeforProtein** [comment]
Functionality may have been stripped on multiple rewrite. Investigate issue.

**Comment by ShakeforProtein** [comment]
Homes are listed but cannot be teleported to. Pls Fix

**Comment by ShakeforProtein** [comment]
Reimplemented sometime between then and now
